// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// estimate_bmdfm
Rcpp::List estimate_bmdfm(int num_chains, int num_iter, int num_burn, int thin, std::vector<Eigen::MatrixXd>& y, int factor_lag, Rcpp::List param_dfm, Rcpp::List dfm_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, Eigen::VectorXi seed_chain, bool display_progress, int nthreads);
RcppExport SEXP _baymar_estimate_bmdfm(SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP ySEXP, SEXP factor_lagSEXP, SEXP param_dfmSEXP, SEXP dfm_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP seed_chainSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::MatrixXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_dfm(param_dfmSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type dfm_init(dfm_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_bmdfm(num_chains, num_iter, num_burn, thin, y, factor_lag, param_dfm, dfm_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, seed_chain, display_progress, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// forecast_bdfm_mniw
Rcpp::List forecast_bdfm_mniw(int num_chains, int step, int nrow_factor, int ncol_factor, int factor_lag, Rcpp::List fit_record, Eigen::VectorXi seed_chain, int nthreads);
RcppExport SEXP _baymar_forecast_bdfm_mniw(SEXP num_chainsSEXP, SEXP stepSEXP, SEXP nrow_factorSEXP, SEXP ncol_factorSEXP, SEXP factor_lagSEXP, SEXP fit_recordSEXP, SEXP seed_chainSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< int >::type nrow_factor(nrow_factorSEXP);
    Rcpp::traits::input_parameter< int >::type ncol_factor(ncol_factorSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_bdfm_mniw(num_chains, step, nrow_factor, ncol_factor, factor_lag, fit_record, seed_chain, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// roll_bdfm_mniw
Rcpp::List roll_bdfm_mniw(Eigen::MatrixXd y, int num_data, int num_chains, int num_iter, int num_burn, int thin, Rcpp::List fit_record, bool run_mcmc, Rcpp::List param_coef_sig, Rcpp::List coef_sig_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, int factor_rows, int factor_cols, int factor_lag, int step, Eigen::MatrixXd y_test, bool get_lpl, Eigen::MatrixXi seed_chain, Eigen::VectorXi seed_forecast, bool display_progress, int nthreads);
RcppExport SEXP _baymar_roll_bdfm_mniw(SEXP ySEXP, SEXP num_dataSEXP, SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP fit_recordSEXP, SEXP run_mcmcSEXP, SEXP param_coef_sigSEXP, SEXP coef_sig_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP factor_rowsSEXP, SEXP factor_colsSEXP, SEXP factor_lagSEXP, SEXP stepSEXP, SEXP y_testSEXP, SEXP get_lplSEXP, SEXP seed_chainSEXP, SEXP seed_forecastSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< bool >::type run_mcmc(run_mcmcSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_coef_sig(param_coef_sigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coef_sig_init(coef_sig_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_rows(factor_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type factor_cols(factor_colsSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y_test(y_testSEXP);
    Rcpp::traits::input_parameter< bool >::type get_lpl(get_lplSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_forecast(seed_forecastSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(roll_bdfm_mniw(y, num_data, num_chains, num_iter, num_burn, thin, fit_record, run_mcmc, param_coef_sig, coef_sig_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, factor_rows, factor_cols, factor_lag, step, y_test, get_lpl, seed_chain, seed_forecast, display_progress, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// expand_bdfm_mniw
Rcpp::List expand_bdfm_mniw(Eigen::MatrixXd y, int num_data, int num_chains, int num_iter, int num_burn, int thin, Rcpp::List fit_record, bool run_mcmc, Rcpp::List param_coef_sig, Rcpp::List coef_sig_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, int factor_rows, int factor_cols, int factor_lag, int step, Eigen::MatrixXd y_test, bool get_lpl, Eigen::MatrixXi seed_chain, Eigen::VectorXi seed_forecast, bool display_progress, int nthreads);
RcppExport SEXP _baymar_expand_bdfm_mniw(SEXP ySEXP, SEXP num_dataSEXP, SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP fit_recordSEXP, SEXP run_mcmcSEXP, SEXP param_coef_sigSEXP, SEXP coef_sig_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP factor_rowsSEXP, SEXP factor_colsSEXP, SEXP factor_lagSEXP, SEXP stepSEXP, SEXP y_testSEXP, SEXP get_lplSEXP, SEXP seed_chainSEXP, SEXP seed_forecastSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< bool >::type run_mcmc(run_mcmcSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_coef_sig(param_coef_sigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coef_sig_init(coef_sig_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_rows(factor_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type factor_cols(factor_colsSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y_test(y_testSEXP);
    Rcpp::traits::input_parameter< bool >::type get_lpl(get_lplSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_forecast(seed_forecastSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_bdfm_mniw(y, num_data, num_chains, num_iter, num_burn, thin, fit_record, run_mcmc, param_coef_sig, coef_sig_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, factor_rows, factor_cols, factor_lag, step, y_test, get_lpl, seed_chain, seed_forecast, display_progress, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// estimate_bmar_mniw
Rcpp::List estimate_bmar_mniw(int num_chains, int num_iter, int num_burn, int thin, std::vector<Eigen::SparseMatrix<double>>& x, std::vector<Eigen::MatrixXd>& y, Rcpp::List param_coef_sig, Rcpp::List coef_sig_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, Rcpp::List exogen_row_prior, Rcpp::List exogen_row_init, int exogen_row_prior_type, int exogen_rows, Rcpp::List exogen_col_prior, Rcpp::List exogen_col_init, int exogen_col_prior_type, int exogen_cols, Rcpp::List factor_row_prior, Rcpp::List factor_row_init, int factor_row_prior_type, int factor_rows, Rcpp::List factor_col_prior, Rcpp::List factor_col_init, int factor_col_prior_type, int factor_cols, int factor_lag, Eigen::VectorXi seed_chain, bool display_progress, int nthreads);
RcppExport SEXP _baymar_estimate_bmar_mniw(SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP xSEXP, SEXP ySEXP, SEXP param_coef_sigSEXP, SEXP coef_sig_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP exogen_row_priorSEXP, SEXP exogen_row_initSEXP, SEXP exogen_row_prior_typeSEXP, SEXP exogen_rowsSEXP, SEXP exogen_col_priorSEXP, SEXP exogen_col_initSEXP, SEXP exogen_col_prior_typeSEXP, SEXP exogen_colsSEXP, SEXP factor_row_priorSEXP, SEXP factor_row_initSEXP, SEXP factor_row_prior_typeSEXP, SEXP factor_rowsSEXP, SEXP factor_col_priorSEXP, SEXP factor_col_initSEXP, SEXP factor_col_prior_typeSEXP, SEXP factor_colsSEXP, SEXP factor_lagSEXP, SEXP seed_chainSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::SparseMatrix<double>>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::MatrixXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_coef_sig(param_coef_sigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coef_sig_init(coef_sig_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_row_prior(exogen_row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_row_init(exogen_row_initSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_row_prior_type(exogen_row_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_rows(exogen_rowsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_col_prior(exogen_col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_col_init(exogen_col_initSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_col_prior_type(exogen_col_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_cols(exogen_colsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_row_prior(factor_row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_row_init(factor_row_initSEXP);
    Rcpp::traits::input_parameter< int >::type factor_row_prior_type(factor_row_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_rows(factor_rowsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_col_prior(factor_col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_col_init(factor_col_initSEXP);
    Rcpp::traits::input_parameter< int >::type factor_col_prior_type(factor_col_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_cols(factor_colsSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_bmar_mniw(num_chains, num_iter, num_burn, thin, x, y, param_coef_sig, coef_sig_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, exogen_row_prior, exogen_row_init, exogen_row_prior_type, exogen_rows, exogen_col_prior, exogen_col_init, exogen_col_prior_type, exogen_cols, factor_row_prior, factor_row_init, factor_row_prior_type, factor_rows, factor_col_prior, factor_col_init, factor_col_prior_type, factor_cols, factor_lag, seed_chain, display_progress, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// forecast_bmar_mniw
Rcpp::List forecast_bmar_mniw(int num_chains, int lag, int step, Eigen::MatrixXd response_mat, int num_data, int nrow_factor, int ncol_factor, int factor_lag, Rcpp::List fit_record, Eigen::VectorXi seed_chain, int nthreads);
RcppExport SEXP _baymar_forecast_bmar_mniw(SEXP num_chainsSEXP, SEXP lagSEXP, SEXP stepSEXP, SEXP response_matSEXP, SEXP num_dataSEXP, SEXP nrow_factorSEXP, SEXP ncol_factorSEXP, SEXP factor_lagSEXP, SEXP fit_recordSEXP, SEXP seed_chainSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type response_mat(response_matSEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< int >::type nrow_factor(nrow_factorSEXP);
    Rcpp::traits::input_parameter< int >::type ncol_factor(ncol_factorSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_bmar_mniw(num_chains, lag, step, response_mat, num_data, nrow_factor, ncol_factor, factor_lag, fit_record, seed_chain, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// forecast_bmarx_mniw
Rcpp::List forecast_bmarx_mniw(int num_chains, int lag, int step, Eigen::MatrixXd response_mat, int num_data, int nrow_factor, int ncol_factor, int factor_lag, Rcpp::List fit_record, Eigen::VectorXi seed_chain, Eigen::MatrixXd exogen, int exogen_lag, int nthreads);
RcppExport SEXP _baymar_forecast_bmarx_mniw(SEXP num_chainsSEXP, SEXP lagSEXP, SEXP stepSEXP, SEXP response_matSEXP, SEXP num_dataSEXP, SEXP nrow_factorSEXP, SEXP ncol_factorSEXP, SEXP factor_lagSEXP, SEXP fit_recordSEXP, SEXP seed_chainSEXP, SEXP exogenSEXP, SEXP exogen_lagSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type response_mat(response_matSEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< int >::type nrow_factor(nrow_factorSEXP);
    Rcpp::traits::input_parameter< int >::type ncol_factor(ncol_factorSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type exogen(exogenSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_lag(exogen_lagSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_bmarx_mniw(num_chains, lag, step, response_mat, num_data, nrow_factor, ncol_factor, factor_lag, fit_record, seed_chain, exogen, exogen_lag, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// roll_bmar_mniw
Rcpp::List roll_bmar_mniw(Eigen::MatrixXd y, int lag, int num_data, int num_chains, int num_iter, int num_burn, int thin, Rcpp::List fit_record, bool run_mcmc, Rcpp::List param_coef_sig, Rcpp::List coef_sig_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, Rcpp::List factor_row_prior, Rcpp::List factor_row_init, int factor_row_prior_type, int factor_rows, Rcpp::List factor_col_prior, Rcpp::List factor_col_init, int factor_col_prior_type, int factor_cols, int factor_lag, int step, Eigen::MatrixXd y_test, bool get_lpl, Eigen::MatrixXi seed_chain, Eigen::VectorXi seed_forecast, bool display_progress, int nthreads);
RcppExport SEXP _baymar_roll_bmar_mniw(SEXP ySEXP, SEXP lagSEXP, SEXP num_dataSEXP, SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP fit_recordSEXP, SEXP run_mcmcSEXP, SEXP param_coef_sigSEXP, SEXP coef_sig_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP factor_row_priorSEXP, SEXP factor_row_initSEXP, SEXP factor_row_prior_typeSEXP, SEXP factor_rowsSEXP, SEXP factor_col_priorSEXP, SEXP factor_col_initSEXP, SEXP factor_col_prior_typeSEXP, SEXP factor_colsSEXP, SEXP factor_lagSEXP, SEXP stepSEXP, SEXP y_testSEXP, SEXP get_lplSEXP, SEXP seed_chainSEXP, SEXP seed_forecastSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< bool >::type run_mcmc(run_mcmcSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_coef_sig(param_coef_sigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coef_sig_init(coef_sig_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_row_prior(factor_row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_row_init(factor_row_initSEXP);
    Rcpp::traits::input_parameter< int >::type factor_row_prior_type(factor_row_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_rows(factor_rowsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_col_prior(factor_col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_col_init(factor_col_initSEXP);
    Rcpp::traits::input_parameter< int >::type factor_col_prior_type(factor_col_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_cols(factor_colsSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y_test(y_testSEXP);
    Rcpp::traits::input_parameter< bool >::type get_lpl(get_lplSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_forecast(seed_forecastSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(roll_bmar_mniw(y, lag, num_data, num_chains, num_iter, num_burn, thin, fit_record, run_mcmc, param_coef_sig, coef_sig_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, factor_row_prior, factor_row_init, factor_row_prior_type, factor_rows, factor_col_prior, factor_col_init, factor_col_prior_type, factor_cols, factor_lag, step, y_test, get_lpl, seed_chain, seed_forecast, display_progress, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// roll_bmarx_mniw
Rcpp::List roll_bmarx_mniw(Eigen::MatrixXd y, int lag, int num_data, int num_chains, int num_iter, int num_burn, int thin, Rcpp::List fit_record, bool run_mcmc, Rcpp::List param_coef_sig, Rcpp::List coef_sig_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, Rcpp::List factor_row_prior, Rcpp::List factor_row_init, int factor_row_prior_type, int factor_rows, Rcpp::List factor_col_prior, Rcpp::List factor_col_init, int factor_col_prior_type, int factor_cols, int factor_lag, int step, Eigen::MatrixXd y_test, bool get_lpl, Eigen::MatrixXi seed_chain, Eigen::VectorXi seed_forecast, bool display_progress, int nthreads, Eigen::MatrixXd exogen, int exogen_lag, Rcpp::List exogen_row_prior, Rcpp::List exogen_row_init, int exogen_row_prior_type, Rcpp::List exogen_col_prior, Rcpp::List exogen_col_init, int exogen_col_prior_type);
RcppExport SEXP _baymar_roll_bmarx_mniw(SEXP ySEXP, SEXP lagSEXP, SEXP num_dataSEXP, SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP fit_recordSEXP, SEXP run_mcmcSEXP, SEXP param_coef_sigSEXP, SEXP coef_sig_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP factor_row_priorSEXP, SEXP factor_row_initSEXP, SEXP factor_row_prior_typeSEXP, SEXP factor_rowsSEXP, SEXP factor_col_priorSEXP, SEXP factor_col_initSEXP, SEXP factor_col_prior_typeSEXP, SEXP factor_colsSEXP, SEXP factor_lagSEXP, SEXP stepSEXP, SEXP y_testSEXP, SEXP get_lplSEXP, SEXP seed_chainSEXP, SEXP seed_forecastSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP, SEXP exogenSEXP, SEXP exogen_lagSEXP, SEXP exogen_row_priorSEXP, SEXP exogen_row_initSEXP, SEXP exogen_row_prior_typeSEXP, SEXP exogen_col_priorSEXP, SEXP exogen_col_initSEXP, SEXP exogen_col_prior_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< bool >::type run_mcmc(run_mcmcSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_coef_sig(param_coef_sigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coef_sig_init(coef_sig_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_row_prior(factor_row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_row_init(factor_row_initSEXP);
    Rcpp::traits::input_parameter< int >::type factor_row_prior_type(factor_row_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_rows(factor_rowsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_col_prior(factor_col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_col_init(factor_col_initSEXP);
    Rcpp::traits::input_parameter< int >::type factor_col_prior_type(factor_col_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_cols(factor_colsSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y_test(y_testSEXP);
    Rcpp::traits::input_parameter< bool >::type get_lpl(get_lplSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_forecast(seed_forecastSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type exogen(exogenSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_lag(exogen_lagSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_row_prior(exogen_row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_row_init(exogen_row_initSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_row_prior_type(exogen_row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_col_prior(exogen_col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_col_init(exogen_col_initSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_col_prior_type(exogen_col_prior_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(roll_bmarx_mniw(y, lag, num_data, num_chains, num_iter, num_burn, thin, fit_record, run_mcmc, param_coef_sig, coef_sig_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, factor_row_prior, factor_row_init, factor_row_prior_type, factor_rows, factor_col_prior, factor_col_init, factor_col_prior_type, factor_cols, factor_lag, step, y_test, get_lpl, seed_chain, seed_forecast, display_progress, nthreads, exogen, exogen_lag, exogen_row_prior, exogen_row_init, exogen_row_prior_type, exogen_col_prior, exogen_col_init, exogen_col_prior_type));
    return rcpp_result_gen;
END_RCPP
}
// expand_bmar_mniw
Rcpp::List expand_bmar_mniw(Eigen::MatrixXd y, int lag, int num_data, int num_chains, int num_iter, int num_burn, int thin, Rcpp::List fit_record, bool run_mcmc, Rcpp::List param_coef_sig, Rcpp::List coef_sig_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, Rcpp::List factor_row_prior, Rcpp::List factor_row_init, int factor_row_prior_type, int factor_rows, Rcpp::List factor_col_prior, Rcpp::List factor_col_init, int factor_col_prior_type, int factor_cols, int factor_lag, int step, Eigen::MatrixXd y_test, bool get_lpl, Eigen::MatrixXi seed_chain, Eigen::VectorXi seed_forecast, bool display_progress, int nthreads);
RcppExport SEXP _baymar_expand_bmar_mniw(SEXP ySEXP, SEXP lagSEXP, SEXP num_dataSEXP, SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP fit_recordSEXP, SEXP run_mcmcSEXP, SEXP param_coef_sigSEXP, SEXP coef_sig_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP factor_row_priorSEXP, SEXP factor_row_initSEXP, SEXP factor_row_prior_typeSEXP, SEXP factor_rowsSEXP, SEXP factor_col_priorSEXP, SEXP factor_col_initSEXP, SEXP factor_col_prior_typeSEXP, SEXP factor_colsSEXP, SEXP factor_lagSEXP, SEXP stepSEXP, SEXP y_testSEXP, SEXP get_lplSEXP, SEXP seed_chainSEXP, SEXP seed_forecastSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< bool >::type run_mcmc(run_mcmcSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_coef_sig(param_coef_sigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coef_sig_init(coef_sig_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_row_prior(factor_row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_row_init(factor_row_initSEXP);
    Rcpp::traits::input_parameter< int >::type factor_row_prior_type(factor_row_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_rows(factor_rowsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_col_prior(factor_col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_col_init(factor_col_initSEXP);
    Rcpp::traits::input_parameter< int >::type factor_col_prior_type(factor_col_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_cols(factor_colsSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y_test(y_testSEXP);
    Rcpp::traits::input_parameter< bool >::type get_lpl(get_lplSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_forecast(seed_forecastSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_bmar_mniw(y, lag, num_data, num_chains, num_iter, num_burn, thin, fit_record, run_mcmc, param_coef_sig, coef_sig_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, factor_row_prior, factor_row_init, factor_row_prior_type, factor_rows, factor_col_prior, factor_col_init, factor_col_prior_type, factor_cols, factor_lag, step, y_test, get_lpl, seed_chain, seed_forecast, display_progress, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// expand_bmarx_mniw
Rcpp::List expand_bmarx_mniw(Eigen::MatrixXd y, int lag, int num_data, int num_chains, int num_iter, int num_burn, int thin, Rcpp::List fit_record, bool run_mcmc, Rcpp::List param_coef_sig, Rcpp::List coef_sig_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, Rcpp::List factor_row_prior, Rcpp::List factor_row_init, int factor_row_prior_type, int factor_rows, Rcpp::List factor_col_prior, Rcpp::List factor_col_init, int factor_col_prior_type, int factor_cols, int factor_lag, int step, Eigen::MatrixXd y_test, bool get_lpl, Eigen::MatrixXi seed_chain, Eigen::VectorXi seed_forecast, bool display_progress, int nthreads, Eigen::MatrixXd exogen, int exogen_lag, Rcpp::List exogen_row_prior, Rcpp::List exogen_row_init, int exogen_row_prior_type, Rcpp::List exogen_col_prior, Rcpp::List exogen_col_init, int exogen_col_prior_type);
RcppExport SEXP _baymar_expand_bmarx_mniw(SEXP ySEXP, SEXP lagSEXP, SEXP num_dataSEXP, SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP fit_recordSEXP, SEXP run_mcmcSEXP, SEXP param_coef_sigSEXP, SEXP coef_sig_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP factor_row_priorSEXP, SEXP factor_row_initSEXP, SEXP factor_row_prior_typeSEXP, SEXP factor_rowsSEXP, SEXP factor_col_priorSEXP, SEXP factor_col_initSEXP, SEXP factor_col_prior_typeSEXP, SEXP factor_colsSEXP, SEXP factor_lagSEXP, SEXP stepSEXP, SEXP y_testSEXP, SEXP get_lplSEXP, SEXP seed_chainSEXP, SEXP seed_forecastSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP, SEXP exogenSEXP, SEXP exogen_lagSEXP, SEXP exogen_row_priorSEXP, SEXP exogen_row_initSEXP, SEXP exogen_row_prior_typeSEXP, SEXP exogen_col_priorSEXP, SEXP exogen_col_initSEXP, SEXP exogen_col_prior_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< bool >::type run_mcmc(run_mcmcSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_coef_sig(param_coef_sigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coef_sig_init(coef_sig_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_row_prior(factor_row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_row_init(factor_row_initSEXP);
    Rcpp::traits::input_parameter< int >::type factor_row_prior_type(factor_row_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_rows(factor_rowsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_col_prior(factor_col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_col_init(factor_col_initSEXP);
    Rcpp::traits::input_parameter< int >::type factor_col_prior_type(factor_col_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type factor_cols(factor_colsSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y_test(y_testSEXP);
    Rcpp::traits::input_parameter< bool >::type get_lpl(get_lplSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_forecast(seed_forecastSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type exogen(exogenSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_lag(exogen_lagSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_row_prior(exogen_row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_row_init(exogen_row_initSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_row_prior_type(exogen_row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_col_prior(exogen_col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type exogen_col_init(exogen_col_initSEXP);
    Rcpp::traits::input_parameter< int >::type exogen_col_prior_type(exogen_col_prior_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_bmarx_mniw(y, lag, num_data, num_chains, num_iter, num_burn, thin, fit_record, run_mcmc, param_coef_sig, coef_sig_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, factor_row_prior, factor_row_init, factor_row_prior_type, factor_rows, factor_col_prior, factor_col_init, factor_col_prior_type, factor_cols, factor_lag, step, y_test, get_lpl, seed_chain, seed_forecast, display_progress, nthreads, exogen, exogen_lag, exogen_row_prior, exogen_row_init, exogen_row_prior_type, exogen_col_prior, exogen_col_init, exogen_col_prior_type));
    return rcpp_result_gen;
END_RCPP
}
// sim_mar_process
std::vector<Eigen::MatrixXd> sim_mar_process(int num_sim, int num_burn, int lag, Eigen::MatrixXd init, Eigen::MatrixXd row_coef, Eigen::MatrixXd col_coef, Eigen::MatrixXd row_sig, Eigen::MatrixXd col_sig, unsigned int seed);
RcppExport SEXP _baymar_sim_mar_process(SEXP num_simSEXP, SEXP num_burnSEXP, SEXP lagSEXP, SEXP initSEXP, SEXP row_coefSEXP, SEXP col_coefSEXP, SEXP row_sigSEXP, SEXP col_sigSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_sim(num_simSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type init(initSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_coef(row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_coef(col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_sig(row_sigSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_sig(col_sigSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_mar_process(num_sim, num_burn, lag, init, row_coef, col_coef, row_sig, col_sig, seed));
    return rcpp_result_gen;
END_RCPP
}
// sim_mar_t_process
std::vector<Eigen::MatrixXd> sim_mar_t_process(int num_sim, int num_burn, int lag, Eigen::MatrixXd init, Eigen::MatrixXd row_coef, Eigen::MatrixXd col_coef, Eigen::MatrixXd sigma, Eigen::MatrixXd omega, double nu, unsigned int seed);
RcppExport SEXP _baymar_sim_mar_t_process(SEXP num_simSEXP, SEXP num_burnSEXP, SEXP lagSEXP, SEXP initSEXP, SEXP row_coefSEXP, SEXP col_coefSEXP, SEXP sigmaSEXP, SEXP omegaSEXP, SEXP nuSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_sim(num_simSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type init(initSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_coef(row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_coef(col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_mar_t_process(num_sim, num_burn, lag, init, row_coef, col_coef, sigma, omega, nu, seed));
    return rcpp_result_gen;
END_RCPP
}
// sim_mdfm_process
Rcpp::List sim_mdfm_process(int num_sim, int num_burn, int lag, Eigen::MatrixXd row_coef, Eigen::MatrixXd col_coef, Eigen::MatrixXd row_sig, Eigen::MatrixXd col_sig, Eigen::MatrixXd factor_init, Eigen::MatrixXd factor_row_coef, Eigen::MatrixXd factor_col_coef, Eigen::MatrixXd factor_row_sig, Eigen::MatrixXd factor_col_sig, unsigned int seed);
RcppExport SEXP _baymar_sim_mdfm_process(SEXP num_simSEXP, SEXP num_burnSEXP, SEXP lagSEXP, SEXP row_coefSEXP, SEXP col_coefSEXP, SEXP row_sigSEXP, SEXP col_sigSEXP, SEXP factor_initSEXP, SEXP factor_row_coefSEXP, SEXP factor_col_coefSEXP, SEXP factor_row_sigSEXP, SEXP factor_col_sigSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_sim(num_simSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_coef(row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_coef(col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_sig(row_sigSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_sig(col_sigSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_init(factor_initSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_row_coef(factor_row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_col_coef(factor_col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_row_sig(factor_row_sigSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_col_sig(factor_col_sigSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_mdfm_process(num_sim, num_burn, lag, row_coef, col_coef, row_sig, col_sig, factor_init, factor_row_coef, factor_col_coef, factor_row_sig, factor_col_sig, seed));
    return rcpp_result_gen;
END_RCPP
}
// sim_mdfm_vec_process
Rcpp::List sim_mdfm_vec_process(int num_sim, int num_burn, int lag, Eigen::MatrixXd row_coef, Eigen::MatrixXd col_coef, Eigen::MatrixXd row_sig, Eigen::MatrixXd col_sig, Eigen::MatrixXd factor_init, Eigen::MatrixXd factor_coef, Eigen::MatrixXd factor_sig, unsigned int seed);
RcppExport SEXP _baymar_sim_mdfm_vec_process(SEXP num_simSEXP, SEXP num_burnSEXP, SEXP lagSEXP, SEXP row_coefSEXP, SEXP col_coefSEXP, SEXP row_sigSEXP, SEXP col_sigSEXP, SEXP factor_initSEXP, SEXP factor_coefSEXP, SEXP factor_sigSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_sim(num_simSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_coef(row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_coef(col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_sig(row_sigSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_sig(col_sigSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_init(factor_initSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_coef(factor_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_sig(factor_sigSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_mdfm_vec_process(num_sim, num_burn, lag, row_coef, col_coef, row_sig, col_sig, factor_init, factor_coef, factor_sig, seed));
    return rcpp_result_gen;
END_RCPP
}
// sim_mdfm_vec_t_process
Rcpp::List sim_mdfm_vec_t_process(int num_sim, int num_burn, int lag, Eigen::MatrixXd row_coef, Eigen::MatrixXd col_coef, Eigen::MatrixXd sigma, Eigen::MatrixXd omega, double nu, Eigen::MatrixXd factor_init, Eigen::MatrixXd factor_coef, Eigen::MatrixXd factor_sig, unsigned int seed);
RcppExport SEXP _baymar_sim_mdfm_vec_t_process(SEXP num_simSEXP, SEXP num_burnSEXP, SEXP lagSEXP, SEXP row_coefSEXP, SEXP col_coefSEXP, SEXP sigmaSEXP, SEXP omegaSEXP, SEXP nuSEXP, SEXP factor_initSEXP, SEXP factor_coefSEXP, SEXP factor_sigSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_sim(num_simSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_coef(row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_coef(col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_init(factor_initSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_coef(factor_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_sig(factor_sigSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_mdfm_vec_t_process(num_sim, num_burn, lag, row_coef, col_coef, sigma, omega, nu, factor_init, factor_coef, factor_sig, seed));
    return rcpp_result_gen;
END_RCPP
}
// sim_famar_vec_process
Rcpp::List sim_famar_vec_process(int num_sim, int num_burn, int lag, Eigen::MatrixXd init, Eigen::MatrixXd row_coef, Eigen::MatrixXd col_coef, Eigen::MatrixXd row_sig, Eigen::MatrixXd col_sig, int factor_lag, Eigen::MatrixXd factor_init, Eigen::MatrixXd factor_row_coef, Eigen::MatrixXd factor_col_coef, Eigen::MatrixXd factor_coef, Eigen::MatrixXd factor_sig, unsigned int seed);
RcppExport SEXP _baymar_sim_famar_vec_process(SEXP num_simSEXP, SEXP num_burnSEXP, SEXP lagSEXP, SEXP initSEXP, SEXP row_coefSEXP, SEXP col_coefSEXP, SEXP row_sigSEXP, SEXP col_sigSEXP, SEXP factor_lagSEXP, SEXP factor_initSEXP, SEXP factor_row_coefSEXP, SEXP factor_col_coefSEXP, SEXP factor_coefSEXP, SEXP factor_sigSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_sim(num_simSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type init(initSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_coef(row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_coef(col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_sig(row_sigSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_sig(col_sigSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_init(factor_initSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_row_coef(factor_row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_col_coef(factor_col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_coef(factor_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_sig(factor_sigSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_famar_vec_process(num_sim, num_burn, lag, init, row_coef, col_coef, row_sig, col_sig, factor_lag, factor_init, factor_row_coef, factor_col_coef, factor_coef, factor_sig, seed));
    return rcpp_result_gen;
END_RCPP
}
// sim_famar_vec_t_process
Rcpp::List sim_famar_vec_t_process(int num_sim, int num_burn, int lag, Eigen::MatrixXd init, Eigen::MatrixXd row_coef, Eigen::MatrixXd col_coef, Eigen::MatrixXd sigma, Eigen::MatrixXd omega, double nu, int factor_lag, Eigen::MatrixXd factor_init, Eigen::MatrixXd factor_row_coef, Eigen::MatrixXd factor_col_coef, Eigen::MatrixXd factor_coef, Eigen::MatrixXd factor_sig, unsigned int seed);
RcppExport SEXP _baymar_sim_famar_vec_t_process(SEXP num_simSEXP, SEXP num_burnSEXP, SEXP lagSEXP, SEXP initSEXP, SEXP row_coefSEXP, SEXP col_coefSEXP, SEXP sigmaSEXP, SEXP omegaSEXP, SEXP nuSEXP, SEXP factor_lagSEXP, SEXP factor_initSEXP, SEXP factor_row_coefSEXP, SEXP factor_col_coefSEXP, SEXP factor_coefSEXP, SEXP factor_sigSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_sim(num_simSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type init(initSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_coef(row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_coef(col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type factor_lag(factor_lagSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_init(factor_initSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_row_coef(factor_row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_col_coef(factor_col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_coef(factor_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type factor_sig(factor_sigSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_famar_vec_t_process(num_sim, num_burn, lag, init, row_coef, col_coef, sigma, omega, nu, factor_lag, factor_init, factor_row_coef, factor_col_coef, factor_coef, factor_sig, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_baymar_estimate_bmdfm", (DL_FUNC) &_baymar_estimate_bmdfm, 17},
    {"_baymar_forecast_bdfm_mniw", (DL_FUNC) &_baymar_forecast_bdfm_mniw, 8},
    {"_baymar_roll_bdfm_mniw", (DL_FUNC) &_baymar_roll_bdfm_mniw, 26},
    {"_baymar_expand_bdfm_mniw", (DL_FUNC) &_baymar_expand_bdfm_mniw, 26},
    {"_baymar_estimate_bmar_mniw", (DL_FUNC) &_baymar_estimate_bmar_mniw, 34},
    {"_baymar_forecast_bmar_mniw", (DL_FUNC) &_baymar_forecast_bmar_mniw, 11},
    {"_baymar_forecast_bmarx_mniw", (DL_FUNC) &_baymar_forecast_bmarx_mniw, 13},
    {"_baymar_roll_bmar_mniw", (DL_FUNC) &_baymar_roll_bmar_mniw, 33},
    {"_baymar_roll_bmarx_mniw", (DL_FUNC) &_baymar_roll_bmarx_mniw, 41},
    {"_baymar_expand_bmar_mniw", (DL_FUNC) &_baymar_expand_bmar_mniw, 33},
    {"_baymar_expand_bmarx_mniw", (DL_FUNC) &_baymar_expand_bmarx_mniw, 41},
    {"_baymar_sim_mar_process", (DL_FUNC) &_baymar_sim_mar_process, 9},
    {"_baymar_sim_mar_t_process", (DL_FUNC) &_baymar_sim_mar_t_process, 10},
    {"_baymar_sim_mdfm_process", (DL_FUNC) &_baymar_sim_mdfm_process, 13},
    {"_baymar_sim_mdfm_vec_process", (DL_FUNC) &_baymar_sim_mdfm_vec_process, 11},
    {"_baymar_sim_mdfm_vec_t_process", (DL_FUNC) &_baymar_sim_mdfm_vec_t_process, 12},
    {"_baymar_sim_famar_vec_process", (DL_FUNC) &_baymar_sim_famar_vec_process, 15},
    {"_baymar_sim_famar_vec_t_process", (DL_FUNC) &_baymar_sim_famar_vec_t_process, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_baymar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
