// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// estimate_bmar_mniw
Rcpp::List estimate_bmar_mniw(int num_chains, int num_iter, int num_burn, int thin, std::vector<Eigen::SparseMatrix<double>>& x, std::vector<Eigen::MatrixXd>& y, Rcpp::List param_coef_sig, Rcpp::List coef_sig_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, Eigen::VectorXi seed_chain, bool display_progress, int nthreads);
RcppExport SEXP _baymar_estimate_bmar_mniw(SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP xSEXP, SEXP ySEXP, SEXP param_coef_sigSEXP, SEXP coef_sig_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP seed_chainSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::SparseMatrix<double>>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::MatrixXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_coef_sig(param_coef_sigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coef_sig_init(coef_sig_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_bmar_mniw(num_chains, num_iter, num_burn, thin, x, y, param_coef_sig, coef_sig_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, seed_chain, display_progress, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// forecast_bmar_mniw
Rcpp::List forecast_bmar_mniw(int num_chains, int lag, int step, Eigen::MatrixXd response_mat, int num_data, Rcpp::List fit_record, Eigen::VectorXi seed_chain, int nthreads);
RcppExport SEXP _baymar_forecast_bmar_mniw(SEXP num_chainsSEXP, SEXP lagSEXP, SEXP stepSEXP, SEXP response_matSEXP, SEXP num_dataSEXP, SEXP fit_recordSEXP, SEXP seed_chainSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type response_mat(response_matSEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_bmar_mniw(num_chains, lag, step, response_mat, num_data, fit_record, seed_chain, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// roll_bmar_mniw
Rcpp::List roll_bmar_mniw(Eigen::MatrixXd y, int lag, int num_data, int num_chains, int num_iter, int num_burn, int thin, Rcpp::List fit_record, bool run_mcmc, Rcpp::List param_coef_sig, Rcpp::List coef_sig_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, int step, Eigen::MatrixXd y_test, Eigen::MatrixXi seed_chain, Eigen::VectorXi seed_forecast, bool display_progress, int nthreads);
RcppExport SEXP _baymar_roll_bmar_mniw(SEXP ySEXP, SEXP lagSEXP, SEXP num_dataSEXP, SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP fit_recordSEXP, SEXP run_mcmcSEXP, SEXP param_coef_sigSEXP, SEXP coef_sig_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP stepSEXP, SEXP y_testSEXP, SEXP seed_chainSEXP, SEXP seed_forecastSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< bool >::type run_mcmc(run_mcmcSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_coef_sig(param_coef_sigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coef_sig_init(coef_sig_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y_test(y_testSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_forecast(seed_forecastSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(roll_bmar_mniw(y, lag, num_data, num_chains, num_iter, num_burn, thin, fit_record, run_mcmc, param_coef_sig, coef_sig_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, step, y_test, seed_chain, seed_forecast, display_progress, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// expand_bmar_mniw
Rcpp::List expand_bmar_mniw(Eigen::MatrixXd y, int lag, int num_data, int num_chains, int num_iter, int num_burn, int thin, Rcpp::List fit_record, bool run_mcmc, Rcpp::List param_coef_sig, Rcpp::List coef_sig_init, Rcpp::List row_prior, Rcpp::List row_init, int row_prior_type, Rcpp::List col_prior, Rcpp::List col_init, int col_prior_type, int step, Eigen::MatrixXd y_test, Eigen::MatrixXi seed_chain, Eigen::VectorXi seed_forecast, bool display_progress, int nthreads);
RcppExport SEXP _baymar_expand_bmar_mniw(SEXP ySEXP, SEXP lagSEXP, SEXP num_dataSEXP, SEXP num_chainsSEXP, SEXP num_iterSEXP, SEXP num_burnSEXP, SEXP thinSEXP, SEXP fit_recordSEXP, SEXP run_mcmcSEXP, SEXP param_coef_sigSEXP, SEXP coef_sig_initSEXP, SEXP row_priorSEXP, SEXP row_initSEXP, SEXP row_prior_typeSEXP, SEXP col_priorSEXP, SEXP col_initSEXP, SEXP col_prior_typeSEXP, SEXP stepSEXP, SEXP y_testSEXP, SEXP seed_chainSEXP, SEXP seed_forecastSEXP, SEXP display_progressSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type num_data(num_dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fit_record(fit_recordSEXP);
    Rcpp::traits::input_parameter< bool >::type run_mcmc(run_mcmcSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type param_coef_sig(param_coef_sigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coef_sig_init(coef_sig_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_prior(row_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type row_init(row_initSEXP);
    Rcpp::traits::input_parameter< int >::type row_prior_type(row_prior_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_prior(col_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type col_init(col_initSEXP);
    Rcpp::traits::input_parameter< int >::type col_prior_type(col_prior_typeSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y_test(y_testSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type seed_chain(seed_chainSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type seed_forecast(seed_forecastSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_bmar_mniw(y, lag, num_data, num_chains, num_iter, num_burn, thin, fit_record, run_mcmc, param_coef_sig, coef_sig_init, row_prior, row_init, row_prior_type, col_prior, col_init, col_prior_type, step, y_test, seed_chain, seed_forecast, display_progress, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// sim_mar_export
std::vector<Eigen::MatrixXd> sim_mar_export(int num_sim, int num_burn, Eigen::SparseMatrix<double> init, Eigen::MatrixXd row_coef, Eigen::MatrixXd col_coef, Eigen::MatrixXd row_sig, Eigen::MatrixXd col_sig);
RcppExport SEXP _baymar_sim_mar_export(SEXP num_simSEXP, SEXP num_burnSEXP, SEXP initSEXP, SEXP row_coefSEXP, SEXP col_coefSEXP, SEXP row_sigSEXP, SEXP col_sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_sim(num_simSEXP);
    Rcpp::traits::input_parameter< int >::type num_burn(num_burnSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type init(initSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_coef(row_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_coef(col_coefSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type row_sig(row_sigSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type col_sig(col_sigSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_mar_export(num_sim, num_burn, init, row_coef, col_coef, row_sig, col_sig));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_baymar_estimate_bmar_mniw", (DL_FUNC) &_baymar_estimate_bmar_mniw, 17},
    {"_baymar_forecast_bmar_mniw", (DL_FUNC) &_baymar_forecast_bmar_mniw, 8},
    {"_baymar_roll_bmar_mniw", (DL_FUNC) &_baymar_roll_bmar_mniw, 23},
    {"_baymar_expand_bmar_mniw", (DL_FUNC) &_baymar_expand_bmar_mniw, 23},
    {"_baymar_sim_mar_export", (DL_FUNC) &_baymar_sim_mar_export, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_baymar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
